# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- Ado

pool:
  vmImage: 'windows-2019'

strategy:
  matrix:
    #Release:
    #  Configuration: Release
    Debug:
      Configuration: Debug

steps:
- task: CMake@1
  inputs:
    displayName: CMake Generate
    workingDirectory: 'CMake'
    cmakeArgs: '-S ../ -B ./bin -G "Visual Studio 16 2019"'
- task: CMake@1
  inputs:
    displayName: CMake Build
    workingDirectory: 'CMake'
    cmakeArgs: '--build ./bin --config $(Configuration)'
#- task: PublishSymbols@2
#  inputs:
#    SearchPattern: '**/bin/**/*.pdb'
#    SymbolServerType: 'TeamServices'
- task: CopyFiles@2
  inputs:
    workingDirectory: 'CMake'
    sourceFolder: './bin/SimpleMeta/$(Configuration)'
    contents: '?(*.exe|*.dll|*.pdb|*.json)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/$(Configuration)'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Configuration)'
    artifactName: '$(Configuration)'
- task: CmdLine@2
  inputs:
    displayName: Run Tests
    workingDirectory: 'CMake'
    #script: '$(Build.ArtifactStagingDirectory)/$(Configuration)/SimpleMeta.exe'
    script: './bin/SimpleMeta/$(Configuration)/SimpleMeta.exe'